package com.hr.entity;

import java.io.Serializable;
import java.util.Date;

public class Users implements Serializable{
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.uid
     *
     * @mbggenerated
     */
    private Integer uid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.uname
     *
     * @mbggenerated
     */
    private String uname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.upass
     *
     * @mbggenerated
     */
    private String upass;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column users.ubirth
     *
     * @mbggenerated
     */
    private Date ubirth;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.uid
     *
     * @return the value of users.uid
     *
     * @mbggenerated
     */
    public Integer getUid() {
        return uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.uid
     *
     * @param uid the value for users.uid
     *
     * @mbggenerated
     */
    public void setUid(Integer uid) {
        this.uid = uid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.uname
     *
     * @return the value of users.uname
     *
     * @mbggenerated
     */
    public String getUname() {
        return uname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.uname
     *
     * @param uname the value for users.uname
     *
     * @mbggenerated
     */
    public void setUname(String uname) {
        this.uname = uname == null ? null : uname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.upass
     *
     * @return the value of users.upass
     *
     * @mbggenerated
     */
    public String getUpass() {
        return upass;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.upass
     *
     * @param upass the value for users.upass
     *
     * @mbggenerated
     */
    public void setUpass(String upass) {
        this.upass = upass == null ? null : upass.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column users.ubirth
     *
     * @return the value of users.ubirth
     *
     * @mbggenerated
     */
    public Date getUbirth() {
        return ubirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column users.ubirth
     *
     * @param ubirth the value for users.ubirth
     *
     * @mbggenerated
     */
    public void setUbirth(Date ubirth) {
        this.ubirth = ubirth;
    }
}