package com.hr.entity;

import java.util.List;

public class Teacher {
    @Override
    public String toString() {
        return "Teacher{" +
                "tid=" + tid +
                ", tname='" + tname + '\'' +
                ", stus=" + stus +
                '}';
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tid
     *
     * @mbggenerated
     */
    private Integer tid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column teacher.tname
     *
     * @mbggenerated
     */
    private String tname;

    private List<Student> stus;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tid
     *
     * @return the value of teacher.tid
     *
     * @mbggenerated
     */
    public Integer getTid() {
        return tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tid
     *
     * @param tid the value for teacher.tid
     *
     * @mbggenerated
     */
    public void setTid(Integer tid) {
        this.tid = tid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column teacher.tname
     *
     * @return the value of teacher.tname
     *
     * @mbggenerated
     */
    public String getTname() {
        return tname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column teacher.tname
     *
     * @param tname the value for teacher.tname
     *
     * @mbggenerated
     */
    public void setTname(String tname) {
        this.tname = tname == null ? null : tname.trim();
    }

    public List<Student> getStus() {
        return stus;
    }

    public void setStus(List<Student> stus) {
        this.stus = stus;
    }
}